version: '2'

networks:
  nginx-proxy_default:
    external: true

services:
  app:
    image: linuxserver/nextcloud
    restart: unless-stopped
    container_name: nextcloud
    # ports:
    #   - 8080:80
    networks:
      nginx-proxy_default:
        ipv4_address: 172.18.0.5
    volumes:
      - /home/huyndg/nas/nextcloud/data:/data
      - /home/huyndg/nas/nextcloud/config:/config
      - /dev/dri/:/dev/dri/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - /home/huyndg/nas/nextcloud:/app
      # - ./nextcloud:/config
    # environment:
    #   - SQLITE_DATABASE=nextcloud
    #   - NEXTCLOUD_ADMIN_USER=admin
    #   - NEXTCLOUD_ADMIN_PASSWORD=hendrix
    #   - OBJECTSTORE_S3_BUCKET=nextcloud
    #   - OBJECTSTORE_S3_HOST=minio-dashboard.huyndg.io.vn
    #   - OBJECTSTORE_S3_PORT=9090
    #   - OBJECTSTORE_S3_KEY=nextcloud
    #   - OBJECTSTORE_S3_SECRET=b5YUw7yiV32K99nWQbgfkfUOof5Z89YN5lSHkQ28
    #   - NEXTCLOUD_TRUSTED_DOMAINS=https://nextcloud.huyndg.io.vn
