

tasks:
  - before: >
      echo "alias ll = 'ls -a -l'" >> ~/.bashrc
      echo "alias gs = 'git status'" >> ~/.bashrc
      echo "alias gl = 'git log'" >> ~/.bashrc

  - name: Install Dependency
    init: yarn install

vscode:
  extensions:
    - christian-kohler.npm-intellisense
      vscode.typescript-language-features
      steoates.autoimport