version: '3.8'


networks:
  net:
  nginx-manager_nginx:
    external: true

volumes:
  minio:

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    networks:
      - net
      - nginx-manager_nginx
    environment:
      - "MINIO_ROOT_USER=admin"
      - "MINIO_ROOT_PASSWORD=admin1234"
    command: server /data --console-address ":9090"
    volumes:
      - minio:/data