version: '3.8'


networks:
  nginx-proxy_default:
    external: true

# volumes:
#   minio:

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    networks:
      nginx-proxy_default:
        ipv4_address: 172.18.0.3
    environment:
      - "MINIO_ROOT_USER=admin"
      - "MINIO_ROOT_PASSWORD=0937172242@Huy"
    command: server /data --console-address ":9090"
    volumes:
      - /home/huyndg/nas/minio:/data