version: "3.8"

networks:
  loki:
  minio_net:
    external: true
  nginx-manager_nginx:
    external: true

services:
  loki:
    image: grafana/loki:2.8.0
    volumes:
      - ./config/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/ds.yaml
    # entrypoint:
    #   - sh
    #   - -euc
    #   - run.sh
    image: grafana/grafana:latest
    networks:
      - loki

  prometheus:
    image: prom/prometheus:latest
    networks:
      - loki
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    # ports:
    #   - "9090"

  tempo:
    image: grafana/tempo:latest
    networks:
      - loki
      - minio_net
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    # ports:
    #   - "14268:14268"  # jaeger ingest
    #   - "3200:3200"   # tempo
    #   - "9095:9095" # tempo grpc
    #   - "4317:4317"  # otlp grpc
    #   - "4318:4318"  # otlp http
    #   - "9411:9411"   # zipkin

  # k6-tracing:
  #   image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
  #   networks:
  #     - loki
  #   environment:
  #     - ENDPOINT=tempo:4317
  #   restart: always
  #   depends_on:
  #     - tempo

  grafana-lb:
    image: hendrixnguyen/nginx-proxy:1.0.0
    networks:
      - loki
      - nginx-manager_nginx
    # labels:
    #   logging: "promtail"
    #   logging_jobname: "containerlogs"
    environment:
      PROXY_MAP: |
        / => grafana:3000/
        /loki/ => loki:3100/
        /prometheus/ => prometheus:9090/
        /otlp-http/ => tempo:4318/
        /otlp-hrpc/ => tempo:4317/
        /zipkin/ => tempo:9411/
