version: '2'

services:
  node-0:
    image: docker.io/bitnami/redis-cluster
    restart: always
    volumes:
      - cluster_data-0:/bitnami/redis/data
    networks:
      - local_stack
    # ports:
    #   - 32805:6379
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-1:
    image: docker.io/bitnami/redis-cluster
    restart: always
    networks:
      - local_stack
    # ports:
    #   - 32806:6379
    volumes:
      - cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-2:
    image: docker.io/bitnami/redis-cluster
    restart: always
    # ports:
    #   - 32807:6379
    networks:
      - local_stack
    volumes:
      - cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-3:
    image: docker.io/bitnami/redis-cluster
    restart: always
    networks:
      - local_stack
    # ports:
    #   - 32808:6379
    volumes:
      - cluster_data-3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-4:
    image: docker.io/bitnami/redis-cluster
    restart: always
    networks:
      - local_stack
    # ports:
    #   - 32809:6379
    volumes:
      - cluster_data-4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-5:
    image: docker.io/bitnami/redis-cluster
    restart: always
    depends_on:
      - node-0
      - node-1
      - node-2
      - node-3
      - node-4
    networks:
      - local_stack
    # ports:
    #   - 32810:6379
    volumes:
      - cluster_data-5:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDISCLI_AUTH=dev'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

  redis-insight:
    image: redislabs/redisinsight:v2
    # image: oblakstudio/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - 54322:5540
    volumes:
      - redis-cluster_app:/app
      - redis-insight_db:/db
    # environment:
    #   - RITRUSTEDORIGINS=https://cluster.huyndg.io.vn,http://cluster.huyndg.io.vn
    #   - RIPROXYENABLE=true
    networks:
      - local_stack

volumes:
  cluster_data-0:
  cluster_data-1:
  cluster_data-2:
  cluster_data-3:
  cluster_data-4:
  cluster_data-5:
  redis-cluster_app:
  redis-insight_db:

networks:
  local_stack:
    external: true

# networks:
#   net:
#     ipam:
#      # driver: default
#       config:
#         - subnet: "172.30.1.0/24"
#         #- subnet: "2001:3984:3989::/64"

