version: '3.9'
services:
  node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    networks:
      - redisnet
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    networks:
      - redisnet
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    networks:
      - redisnet
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-3:
    image: docker.io/bitnami/redis-cluster:7.0
    networks:
      - redisnet
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-4:
    image: docker.io/bitnami/redis-cluster:7.0
    networks:
      - redisnet
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'

  node-5:
    image: docker.io/bitnami/redis-cluster:7.0
    networks:
      - redisnet
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - node-0
      - node-1
      - node-2
      - node-3
      - node-4
    environment:
      - 'REDIS_PASSWORD=dev'
      - 'REDISCLI_AUTH=dev'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=node-0 node-1 node-2 node-3 node-4 node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-cluster_data-0:
  redis-cluster_data-1:
  redis-cluster_data-2:
  redis-cluster_data-3:
  redis-cluster_data-4:
  redis-cluster_data-5:

networks:
    redisnet:
