version: '3.8'

services:
  stack-redis:
    container_name: redis-stack
    #image: redis/redis-stack:latest
    image: redis/redis-stack-server
    #ports:
      # - 6379:6379
      #- 54321:8001
    networks:
      - local_stack
    restart: always

networks:
  local_stack:
    external: true
