version: '3.8'

services:
  # stack-redis:
  #   container_name: redis-stack
  #   image: redis/redis-stack:latest
  #   ports:
  #     - 16379:6379
  #     - 8001:8001



networks:
  redis-cluster_net:
    external: true
  nginx-manager_nginx:
    external: true
