version: '3.9'

services:
  stack-redis:
    container_name: redis-stack
    image: redis/redis-stack:latest
    networks:
      - redis-cluster_redisnet
    ports:
      - 10001:6379
      - 13333:8001

  redis-insight-v1:
    container_name: redis-insight-v1
    image: redislabs/redisinsight
    networks:
      - redis-cluster_redisnet
    ports:
      - 13334:8001

networks:
  redis-cluster_redisnet:
    external: true