version: '3.8'

services:
  stack-redis:
    container_name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - redis_cluster-net
    restart: always

networks:
  redis_cluster-net:
    external: true
