version: '3.9'

services:
  stack-redis:
    container_name: redis-stack
    image: redis/redis-stack:latest
    networks:
      - redisstack
    ports:
      - 16379:6379
      - 8001:8001

  redis-insight-v1:
    container_name: redis-insight-v1
    image: redislabs/redisinsight
    networks:
      - rediscluster_redisnet
    ports:
      - 18001:8001

networks:
  rediscluster_redisnet:
    external: true
  redisstack:
